gitSourceBranch = "main"

[docusaurus]
url = "https://raild3x.github.io"
baseUrl = "/ModulesOnRails"


[[classOrder]]
classes = ["BaseObject"]

[[classOrder]]
classes = ["Roam"]

[[classOrder]]
section = "TableManager"
classes = ["TableManager", "TableState"]

[[classOrder]]
section = "TableReplicator"
classes = ["TableReplicator", "ServerTableReplicator", "ClientTableReplicator", "TableReplicatorSingleton", "BaseTableReplicator"]

[[classOrder]]
section = "NetWire"
classes = ["NetWire", "ServerNetWire", "ClientNetWire", "----------------", "ServerRemoteEvent", "ServerRemoteProperty", "ClientRemoteEvent", "ClientRemoteProperty"]

[[classOrder]]
section = "Instance Component Systems"
classes = ["Component", "RemoteComponent", "BaseComponent"]

[[classOrder]]
section = "DropletManager"
classes = ["DropletManager", "DropletServerManager", "DropletClientManager", "Droplet", "DropletUtil", "ExampleResourceTypeData"]

[[classOrder]]
section = "AdjustableTimer [Unreleased]"
classes = ["AdjustableTimer", "AdjustableTimerManager"]


[[classOrder]]
section = "PlayerDataManagement [Unreleased]"
classes = ["PlayerProfileManager", "PlayerDataManager", "ServerPlayerDataManager", "ClientPlayerDataManager"]


[[classOrder]]
section = "Admin Commands [Cmdr]"
classes = ["CmdrHandler", "PermissionsHandler", "CmdrServer", "CmdrClient", "CmdrTypes"]

[[classOrder]]
section = "Data Structures"
classes = ["Queue", "Heap", "LooseTightDoubleGrid"]