name: Docs

on:
  push:
    branches:
    - main

jobs:
  generate_readme:
    name: Generate README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bash
        run: sudo apt-get install -y bash

      - name: Set execute permission for script
        run: chmod +x scripts/generateReadMe.sh

      - name: Run generateReadMe.sh
        run: scripts/generateReadMe.sh

      - name: Commit README update
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Update README from GitHub Actions"
          git push

  build:
    name: Build and deploy docs
    runs-on: ubuntu-latest
    needs: generate_readme
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm i -g moonwave@latest
      - name: Publish
        run: |
          git remote set-url origin https://git:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
          git config --global user.email "support+actions@github.com"
          git config --global user.name "github-actions-bot"
          moonwave build --publish
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}